version: "3.9"

services:
  postgres:
    user: postgres
    build:
      context: ./Docker/postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgres-data/:/var/lib/postgresql/data

  redis:
    image: redis
    restart: unless-stopped
    ports:
      - 6379:6379