// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ExchangeClient is the client API for Exchange service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExchangeClient interface {
	// current exchange rate given any two supported currencies
	GetRate(ctx context.Context, in *RateRequest, opts ...grpc.CallOption) (*ExchangeRate, error)
	// list of current exchange rates for base currency
	GetRates(ctx context.Context, in *RatesRequest, opts ...grpc.CallOption) (*ExchangeRates, error)
	// will use stream for practice
	GetHistoricalRates(ctx context.Context, in *RatesRequest, opts ...grpc.CallOption) (Exchange_GetHistoricalRatesClient, error)
}

type exchangeClient struct {
	cc grpc.ClientConnInterface
}

func NewExchangeClient(cc grpc.ClientConnInterface) ExchangeClient {
	return &exchangeClient{cc}
}

func (c *exchangeClient) GetRate(ctx context.Context, in *RateRequest, opts ...grpc.CallOption) (*ExchangeRate, error) {
	out := new(ExchangeRate)
	err := c.cc.Invoke(ctx, "/exchange.Exchange/GetRate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exchangeClient) GetRates(ctx context.Context, in *RatesRequest, opts ...grpc.CallOption) (*ExchangeRates, error) {
	out := new(ExchangeRates)
	err := c.cc.Invoke(ctx, "/exchange.Exchange/GetRates", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exchangeClient) GetHistoricalRates(ctx context.Context, in *RatesRequest, opts ...grpc.CallOption) (Exchange_GetHistoricalRatesClient, error) {
	stream, err := c.cc.NewStream(ctx, &Exchange_ServiceDesc.Streams[0], "/exchange.Exchange/GetHistoricalRates", opts...)
	if err != nil {
		return nil, err
	}
	x := &exchangeGetHistoricalRatesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Exchange_GetHistoricalRatesClient interface {
	Recv() (*ExchangeRates, error)
	grpc.ClientStream
}

type exchangeGetHistoricalRatesClient struct {
	grpc.ClientStream
}

func (x *exchangeGetHistoricalRatesClient) Recv() (*ExchangeRates, error) {
	m := new(ExchangeRates)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ExchangeServer is the server API for Exchange service.
// All implementations must embed UnimplementedExchangeServer
// for forward compatibility
type ExchangeServer interface {
	// current exchange rate given any two supported currencies
	GetRate(context.Context, *RateRequest) (*ExchangeRate, error)
	// list of current exchange rates for base currency
	GetRates(context.Context, *RatesRequest) (*ExchangeRates, error)
	// will use stream for practice
	GetHistoricalRates(*RatesRequest, Exchange_GetHistoricalRatesServer) error
	mustEmbedUnimplementedExchangeServer()
}

// UnimplementedExchangeServer must be embedded to have forward compatible implementations.
type UnimplementedExchangeServer struct {
}

func (UnimplementedExchangeServer) GetRate(context.Context, *RateRequest) (*ExchangeRate, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRate not implemented")
}
func (UnimplementedExchangeServer) GetRates(context.Context, *RatesRequest) (*ExchangeRates, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRates not implemented")
}
func (UnimplementedExchangeServer) GetHistoricalRates(*RatesRequest, Exchange_GetHistoricalRatesServer) error {
	return status.Errorf(codes.Unimplemented, "method GetHistoricalRates not implemented")
}
func (UnimplementedExchangeServer) mustEmbedUnimplementedExchangeServer() {}

// UnsafeExchangeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExchangeServer will
// result in compilation errors.
type UnsafeExchangeServer interface {
	mustEmbedUnimplementedExchangeServer()
}

func RegisterExchangeServer(s grpc.ServiceRegistrar, srv ExchangeServer) {
	s.RegisterService(&Exchange_ServiceDesc, srv)
}

func _Exchange_GetRate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExchangeServer).GetRate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/exchange.Exchange/GetRate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExchangeServer).GetRate(ctx, req.(*RateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exchange_GetRates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExchangeServer).GetRates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/exchange.Exchange/GetRates",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExchangeServer).GetRates(ctx, req.(*RatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exchange_GetHistoricalRates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RatesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ExchangeServer).GetHistoricalRates(m, &exchangeGetHistoricalRatesServer{stream})
}

type Exchange_GetHistoricalRatesServer interface {
	Send(*ExchangeRates) error
	grpc.ServerStream
}

type exchangeGetHistoricalRatesServer struct {
	grpc.ServerStream
}

func (x *exchangeGetHistoricalRatesServer) Send(m *ExchangeRates) error {
	return x.ServerStream.SendMsg(m)
}

// Exchange_ServiceDesc is the grpc.ServiceDesc for Exchange service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Exchange_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "exchange.Exchange",
	HandlerType: (*ExchangeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRate",
			Handler:    _Exchange_GetRate_Handler,
		},
		{
			MethodName: "GetRates",
			Handler:    _Exchange_GetRates_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetHistoricalRates",
			Handler:       _Exchange_GetHistoricalRates_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/exchange.proto",
}
